### ISSUE TITLE
开发者模式：安装FFMPEG和ImageMagic，都是windows的安装程序，没有linux程序的描述

### ISSUE THREAD

**Issue by gavid0124** [FutureUniant/Tailor#3]
如题

**Comment by FutureUniant** [comment]
对于FFMPEG和ImageMagic，目前是没有在Linux系统上使用和测试过的。
如果希望使用Linux来启动Tailor，可以直接查询FFMPEG和ImageMagic的Linux安装就可以了。目前没有针对这两个库进行修改，因此使用通用的安装方法就可以。
附：
1. [FFMPEG官方下载网址](https://www.ffmpeg.org/download.html#build-linux)
2. ImageMagic安装命令：sudo apt install imagemagick

同时需要注意一下两点内容：
1. tailor/app/utils/paths.py内关于FFMPEG和ImageMagic的引入路径修改；
2. tailor/main.py内ImageMagic的引入路径修改。

感谢您的提问，有问题可以随时提问！

**Comment by gavid0124** [comment]
感谢您，我试下。
