### ISSUE TITLE
mtcnn使用的问题

### ISSUE THREAD

**Issue by echo233** [FutureUniant/Tailor#5]
您好，在app/src/algorithm/video_cut_face/face_analysis.py脚本中的131行的face_tensors, probs, boxes = self.mtcnn(frame, return_prob=True, return_boxes=True)代码中，mtcnn没有return_boxes这个参数，并且返回值也不是三个

**Comment by SagarChandra07** [comment]
install this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme
I put the necessary dlls in the archive

**Comment by FutureUniant** [comment]
MTCNN的代码进行了修改，可以加群或者微信解答！
![微信图片_20240920220300](https://github.com/user-attachments/assets/080938eb-ddf0-4a7b-abd1-dc1c5c9ae36d)
